[package]
name = "mirp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
dashmap = "6.1.0"
dotenvy = "0.15.7"
lazy_static = "1.5.0"
log = "0.4.29"
log4rs = "1.4.0"
notify = "8.2.0"
tokio = { version = "1.48.0", features = ["full"] }
valence = "0.1.0"
